apiVersion: v1
kind: Secret
metadata:
  name: kube-apiserver
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  server.crt: {{ pki "kube-apiserver-server.crt" }}
  server.key: {{ pki "kube-apiserver-server.key" }}
  kubelet-client.crt: {{ pki "kube-apiserver-kubelet.crt" }}
  kubelet-client.key: {{ pki "kube-apiserver-kubelet.key" }}
  etcd-client.crt: {{ pki "etcd-client.crt" }}
  etcd-client.key: {{ pki "etcd-client.key" }}
  proxy-client.crt: {{ pki "kube-apiserver-aggregator-proxy-client.crt" }}
  proxy-client.key: {{ pki "kube-apiserver-aggregator-proxy-client.key" }}
